### ISSUE TITLE
Uncaught Exception

### ISSUE THREAD

**Issue by skadefro** [shinyoshiaki/rainy-webrtc#374]
How do we catch this error ?
I need a way to avoid this crashing the nodejs application when there is network issues or the stun/turn server is restarted.
channel.onerror is not triggered, so must be something else 

node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

TransactionFailed [Error]
    at Transaction.value [as responseReceived] (/mnt/data/vscode/config/workspace/code/jupyter-agent/node_modules/werift/lib/ice/src/stun/transaction.js:79:47)
    at TurnClient.handleSTUNMessage (/mnt/data/vscode/config/workspace/code/jupyter-agent/node_modules/werift/lib/ice/src/turn/protocol.js:259:33)
    at TurnClient.datagramReceived (/mnt/data/vscode/config/workspace/code/jupyter-agent/node_modules/werift/lib/ice/src/turn/protocol.js:278:18)
    at transport.onData (/mnt/data/vscode/config/workspace/code/jupyter-agent/node_modules/werift/lib/ice/src/turn/protocol.js:240:18)
    at Socket.<anonymous> (/mnt/data/vscode/config/workspace/code/jupyter-agent/node_modules/werift/lib/ice/src/transport.js:80:22)
    at Socket.emit (node:events:514:28)
    at UDP.onMessage [as onmessage] (node:dgram:933:8)
    at UDP.callbackTrampoline (node:internal/async_hooks:130:17) {

**Comment by koush** [comment]
duplicate https://github.com/shinyoshiaki/werift-webrtc/issues/364
